Keep Ubuntu 18.04 around for TensorRT
https://gitlab.com/nvidia/container-images/cuda/-/issues/99

diff --git a/ci/docker/Dockerfile.build.ubuntu b/ci/docker/Dockerfile.build.ubuntu
--- a/ci/docker/Dockerfile.build.ubuntu
+++ b/ci/docker/Dockerfile.build.ubuntu
@@ -124,25 +124,30 @@ COPY runtime_functions.sh /work/
 FROM base as gpu
 
 # Install TensorRT and CuDNN
+# Use bash as it has better support for string comparisons in if clauses
+SHELL ["/bin/bash", "-c"]
 # We need to redeclare ARG due to
 # https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
 ARG BASE_IMAGE
 RUN export SHORT_CUDA_VERSION=${CUDA_VERSION%.*} && \
+    export OS_VERSION="$(cat /proc/version)" && \
     apt-get update && \
-    if [ ${SHORT_CUDA_VERSION} = 11.0 ]; then \
-        TRT_VERSION="7.2.0-1+cuda11.0"; \
-        TRT_MAJOR_VERSION=7; \
-    elif [ ${SHORT_CUDA_VERSION} = 11.1 ]; then \
-        TRT_VERSION="7.2.0-1+cuda11.1"; \
-        TRT_MAJOR_VERSION=7; \
-    else \
-        echo "ERROR: Cuda ${SHORT_CUDA_VERSION} not yet supported in Dockerfile.build.ubuntu"; \
-        exit 1; \
+    if [[ ${OS_VERSION} == *"18.04"* ]]; then \
+        if [ ${SHORT_CUDA_VERSION} = 11.0 ]; then \
+            TRT_VERSION="7.2.0-1+cuda11.0"; \
+            TRT_MAJOR_VERSION=7; \
+        elif [ ${SHORT_CUDA_VERSION} = 11.1 ]; then \
+            TRT_VERSION="7.2.1-1+cuda11.1"; \
+            TRT_MAJOR_VERSION=7; \
+        else \
+            echo "ERROR: Cuda ${SHORT_CUDA_VERSION} not yet supported in Dockerfile.build.ubuntu"; \
+            exit 1; \
+        fi; \
+        apt-get install -y libnvinfer${TRT_MAJOR_VERSION}=${TRT_VERSION} \
+                           libnvinfer-dev=${TRT_VERSION} \
+                           libnvinfer-plugin${TRT_MAJOR_VERSION}=${TRT_VERSION} \
+                           libnvinfer-plugin-dev=${TRT_VERSION}; \
     fi && \
-    apt-get install -y libnvinfer${TRT_MAJOR_VERSION}=${TRT_VERSION} \
-                       libnvinfer-dev=${TRT_VERSION} \
-                       libnvinfer-plugin${TRT_MAJOR_VERSION}=${TRT_VERSION} \
-                       libnvinfer-plugin-dev=${TRT_VERSION} \
-                       libcudnn8-dev && \
+    apt-get install -y libcudnn8-dev && \
     rm -rf /var/lib/apt/lists/*
 
